# Generated by Django 2.0.2 on 2018-02-17 22:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Jméno')),
                ('token', models.CharField(blank=True, max_length=32, verbose_name='Token')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Tagy')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Kolekce',
                'verbose_name_plural': 'Kolekce',
                'db_table': 'collection',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Jméno')),
                ('vobject', models.TextField(verbose_name='Vobject')),
                ('etag', models.CharField(max_length=32, verbose_name='Etag')),
                ('history_etag', models.CharField(blank=True, max_length=32, verbose_name='History Etag')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diary.Collection', verbose_name='Kolekce')),
            ],
            options={
                'verbose_name': 'Záznam',
                'verbose_name_plural': 'Záznamy',
                'db_table': 'item',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Jméno')),
                ('item', models.CharField(max_length=254, verbose_name='Záznam')),
                ('etag', models.CharField(max_length=32, verbose_name='Etag')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Vytvořeno')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='diary.Collection', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokeny',
                'db_table': 'token',
                'ordering': ('-id',),
            },
        ),
    ]
