# Generated by Django 2.2.1 on 2019-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180612_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection',
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ManyToManyField(related_name='items', to='diary.Collection', verbose_name='Kolekce'),
        ),
    ]
