# Generated by Django 2.0.6 on 2018-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='users', to='diary.Collection', verbose_name='Kolekce'),
        ),
    ]
